### ISSUE TITLE
Request for PDF versions of documentation.

### ISSUE THREAD

**Issue by MarkxHudson** [booksbyus/zguide#19]
For PDFer's, it would be bonus to have an official PDF version of all 0MQ documentation.

**Comment by jmbeach** [comment]
That link is broken. I understand this might be an annoying comment to post almost a decade later.

**Comment by sappo** [comment]
With the migration to gohugo.io last year we lost the possibility to
generate PDFs for the zguide.

Maybe I can script something together with pandoc but I won't have time to
do this anytime soon.

Jared Beach <notifications@github.com> schrieb am Mo., 1. Feb. 2021, 02:19:

**Comment by jmbeach** [comment]
Oh, so does the ./bin/buildpdfs command generate outdated documentation or something? I got that to build me a PDF / epub yesterday

**Comment by sappo** [comment]
It should be almost up to date. There weren't any major changes lately.
