### ISSUE TITLE
Java examples build scrip can not download  jzmq-2.1.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by hrgdavor** [booksbyus/zguide#382]
scripts calls
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.zeromq&a=jzmq&v=2.1.1-SNAPSHOT&e=jar
to download jzmq-2.1.1-SNAPSHOT.jar
website gives error: 
404 - Not Found

Path /org/zeromq/jzmq/2.1.1-SNAPSHOT/jzmq-2.1.1-SNAPSHOT.jar not found in local storage of repository "Snapshots" [id=snapshots]

Workarround: downloaded the jar by hand from:
http://repo1.maven.org/maven2/org/zeromq/jzmq/2.1.1/jzmq-2.1.1.jar

**Comment by esahekmat** [comment]
I corrected this issue in #730 PR
