### ISSUE TITLE
hwserver.js Missing from node.js examples on site

### ISSUE THREAD

**Issue by seriousmumbo** [booksbyus/zguide#474]
http://zguide.zeromq.org/js:_start

It's here on Github, but the link is missing on the site!

**Comment by xamgore** [comment]
@ghost, the link is present, so this issue can be closed, yeah?

![image](https://user-images.githubusercontent.com/4586392/64072934-d5c78580-cc9f-11e9-8422-6e12eb845acc.png)

**Comment by sappo** [comment]
Thanks for looking at the open issues. I'm closing it.
