### ISSUE TITLE
Missing quote from msgpack.org

### ISSUE THREAD

**Issue by karjaneth** [booksbyus/zguide#621]
The guide references a quote from [msgpack.org](http://msgpack.org/) when discussing [serialization libraries](http://zguide.zeromq.org/py:all#Serialization-Libraries), but the quote is missing. It appears the quote was present in [past versions](http://web.archive.org/web/20121121024948/http://zguide.zeromq.org/py:all#Serialization-Libraries) of the guide, and the text of the quote is still present on the msgpack website.

It was probably removed by accident and should be restored, but if there is some good reason for why it was originally removed, maybe the reference to the quote should be replaced with a link to their site?

**Comment by esahekmat** [comment]
your right, I think a missing whitespace cause this. I create a #744  PR for that
