### ISSUE TITLE
identity.py example uses DEALER instead of REQ

### ISSUE THREAD

**Issue by kishkin** [booksbyus/zguide#644]
Hello,

I'm going through the examples in Python and have noticed that output of identity.py does not comply with the output used in the book (no zero-length second part of multipart-message).

I believe it is because in identity.py example DEALER sockets are used instead of REQ sockets. In C,  C++, and C# examples REQ sockets are used.

Thanks.

**Comment by mohanagr** [comment]
Should be closed now.
