### ISSUE TITLE
Small error in Hello World server for Java

### ISSUE THREAD

**Issue by phax** [booksbyus/zguide#657]
Page: http://zguide.zeromq.org/java:hwserver
Instead of 
```java
System.out.println("Received Hello");
```
I assume it should be
```java
System.out.println ("Received " + new String (request));
```

**Comment by sappo** [comment]
Great catch! Please send a pull request with the fix. Thanks!

**Comment by phax** [comment]
PR #658

**Comment by phax** [comment]
Should be updated in jeromq as well
