### ISSUE TITLE
C example for Multithreaded zmq client

### ISSUE THREAD

**Issue by jawadatgithub** [booksbyus/zguide#665]
I want C example for Multithreaded zmq client, I am already using Multithreaded server, but I have requirements to make each client send requests from multithreads not single thread.

I had look to:
http://zguide.zeromq.org/c:asyncsrv
https://github.com/booksbyus/zguide/blob/master/examples/C/

but I didn't see client example that uses multithreads of ZMQ_DEALER socket talking to Multithreaded server (ZMQ_ROUTER socket)

so I am looking for DEALER and ROUTER pattern. I want the client (DEALER) to be multithreaded:
if I follow same analogy of multi-threaded server example, I need proxy that bind multi dealers threads, correct?

currently my client is similar to hello world C:

```
	ctx = zctx_new ();
	client = zsocket_new (ctx, ZMQ_REQ);
	assert (client);
	zsocket_connect (client, config.SERVER_ENDPOINT);

        // SKIPPED: I get the data (hm->body.p) to be send though zmq...

	//  We send a request, then we work to get a reply
	zstr_sendf(client, "%.*s", (int) hm->body.len,hm->body.p);
        char *reply = zstr_recv (client);
        if (reply)	{
                zsys_info ("server replied (%s)", reply);
	        free (reply);
	 } 
```

Please help me make my C client  to be Multithreaded zmq client

**Comment by sappo** [comment]
Hi @jawadatgithub, have a look at czmq actors (https://github.com/zeromq/czmq#toc4-242, https://github.com/zeromq/czmq#toc2-8254) this is what you're looking for.

**Comment by jawadatgithub** [comment]
I posted more details in below stackoverflow question:
http://stackoverflow.com/questions/40404493/zmq-multithread-c-client

I will look to both links you shared.
