### ISSUE TITLE
"Getting the Context Right" restrictions

### ISSUE THREAD

**Issue by dherity** [booksbyus/zguide#670]
I'm working on unit tests for code that uses 0mq and  I'm finding the zguide section "Getting the Context Right" pretty restrictive.

1. A process can only have one context.
2. The context must be created once and destroyed once in a process.
3. The context must be created after any fork.

Each of my tests creates and destroys a context.
Some of the tests fork to create a process to talk to.
All the tests work, but clearly, I'm skiing off piste.

Restrictions 1 and 2 can be got around using reference counting, but restriction 3 is the last straw.
Is there any wiggle room here? If, for example, it were possible to create and destroy a context more than once, I could meet the other restrictions without exposing them to the application.

**Comment by sappo** [comment]
@dherity have a look at czmq (http://github.com/zeromq/czmq) which is the high-level C-API for ZeroMQ. We already solved all of your problems :)

1./ 2. One context is automatically created and destroyed 
3. Use zactor threads with a communication pipe instead of forks

**Comment by dherity** [comment]
@sappo Thanks for that, but I'm hoping for a solution that doesn't involve involve eliminating fork and adding another library.

**Comment by sappo** [comment]
The current architecture of libzmq doesn't allow to share a context between processes or forks. We slowly working to get rid this constraint but not any time soon. Why don't you create the context after forking?

**Comment by sappo** [comment]
Sorry, just answered myself! In czmq we test using either threads or just sequential I/O using the inproc protocol.

**Comment by dherity** [comment]
In my case, the fork is in a test and tests can be run in any order.
Anyway, I accept that what I want to do isn't feasible, so I'm getting rid of the fork - using thread instead.
Thanks for your help.
