### ISSUE TITLE
[translation] Rust examples

### ISSUE THREAD

**Issue by dowoncha** [booksbyus/zguide#677]
I would like to contribute rust examples by implementing the hwclient.c in the C examples. I am unsure how example building is handled in this project. Rust projects are started using cargo init in the project root, can i create a Cargo.toml file in the rust folder?

**Comment by sappo** [comment]
Hi @dowoncha, that's great. If you like to implement the rust version of `hwclient` just add it to the `examples/rust` folder. I.e. `examples/rust/hwclient.rust` or whatever is the correct rust fileending. I'll take care of the remains.

**Comment by dowoncha** [comment]
It looks like somebody has already created bindings at https://github.com/erickt/rust-zmq along with examples.

**Comment by sappo** [comment]
If you like these examples to show up in the zguide they would need to be copied to the `examples/rust` folder.

**Comment by jrast** [comment]
Seems like the examples where added in `examples/rust` but they are not visible on the homepage?
