### ISSUE TITLE
assertion failure in signaler_t.cpp

### ISSUE THREAD

**Issue by vkhalidov** [booksbyus/zguide#683]
Hello,
I'm using 0MQ (4.2.0) with wine (wine-1.8) on Ubuntu 14.04.5 to perform socket communication. The communication is performed between a DLL module (that is shut down and relaunched regularly) that is loaded by an executable that runs under wine and another process that runs directly on Ubuntu. Thus the sockets used in the communication are regularly closed and reopened. Everything works as expected 99% of time. However, sometimes the DLL produces assertion failure when shutting down the socket and blocks, requiring manual restart:
Assertion failed: Bad file number (..\..\..\..\src\signaler.cpp:185)

After having investigated a bit, I found out that there is an io_thread inside 0MQ that tries to send a command after the socket has been destroyed, which causes the assertion failure (the winsock send method returns an error code when trying to send anything to a closed socket, which is checked against in the assert statement).

I observe the following sequence of calls before the problem occurs:
1. The main thread (DLL module) creates a signaler that calls unblock_socket on the system write socket W
2. Soon an io_thread is launched in a system thread A (that performs zmq::select_t::loop), it calls signaler_t::send regularly, using this system socket handler W.
3. After some time a reaper io_thread is created in a system thread B (also performs zmq::select_t::loop) that calls zmq::socket_base_t::start_reaping and destroys the socket (zmq::socket_base_t::check_destroy, signaler_t::~signaler_t), which closes the system write socket W
4. All of the sudden, after the socket is already destroyed, the io_thread in a system thread A calls signaler_t::send with the system write socket W that has already been closed, which produces the assertion.

It looks like the io_thread that used system thread A is somehow not aware of the fact that the socket has already been destroyed. This is reproduced only with a particular sequence of calls, so sometimes it can run for 2 days without any problem (having hundreds or socket open/close operations succeeded) and all of the sudden encounter the assertion. I did not go deep into the code to analyze how io_threads implement safety measures in order to prevent sending anything to closed sockets. But any insight on where to look and which invariant to check would be of great help!

Best regards,
Vasil

**Comment by sappo** [comment]
Hi @vkhalidov, thanks for reporting this issue! As this issue is not regarding the zguide I ask you to open this issue in the regarding issue tracker of the project which is libzmq if I'm not mistaken (http://github.com/zeromq/libzmq)

**Comment by vkhalidov** [comment]
Oups, sorry for that! And thanks for the fast reply and for the link!
