### ISSUE TITLE
c++ example for v3.2.5

### ISSUE THREAD

**Issue by lstrcat** [booksbyus/zguide#684]
i found in the mdcliapi.hpp 
`s_version_assert (4, 0);` 

but i use the stable release v3.2.5 ,can you give me a  "Majordomo Pattern" example for 3.2.5?

**Comment by sappo** [comment]
As far as I can see in the git history this example has been upgraded from
2.1 to 4.x directly. If you need help getting the example running I suggest
writing to the mailing list or posting an issue on the regarding project's
issues tracker. This issue tracker is rather low frequency and sadly I
don't know cpp.

Am 15.02.2017 04:08 schrieb "lstrcat" <notifications@github.com>:

**Comment by lstrcat** [comment]
Tks! i think i should change to Release 4.2.1
