### ISSUE TITLE
Grammatical error in Chapter 2

### ISSUE THREAD

**Issue by sush-lala** [booksbyus/zguide#688]
Statement "in ZeroMQ, all your sockets are belong to us" must be "in ZeroMQ, all your sockets ~~are~~ belong to us"

**Comment by sappo** [comment]
Would you mind sending a PR. Thanks!

**Comment by nickray** [comment]
This is "error" is probably a play on this meme: https://en.wikipedia.org/wiki/All_your_base_are_belong_to_us
