### ISSUE TITLE
cannot build C examples

### ISSUE THREAD

**Issue by NikkyAI** [booksbyus/zguide#706]
i assume that the examples are probably only suitable for older versions of `czmq` and `zeromq`
error when compiling eg. clonesrv6
` error: unknown type name ‘zctx_t’; did you mean ‘zrex_t’?`

`Current 0MQ version is 4.2.2`

installed packages:
```
pacaur -Q | grep mq
czmq 4.0.2-1
zeromq 4.2.2-1
```

**Comment by NikkyAI** [comment]
sorry seems related to #701

**Comment by sappo** [comment]
@NikkyAI no worries. Yes its related you can take my project as a start (https://github.com/sappo/czmq_zguide_examples). Currently only the Lazy Pirate Pattern is migrated.
