### ISSUE TITLE
Java examples class name starts with lowercase

### ISSUE THREAD

**Issue by esahekmat** [booksbyus/zguide#724]
java examples class names starts with lowercase however java standard conventions states class name and file name should starts with capitalcase. I think it's because build process. but I can't understand the mechanism. Is there any possible soloution to change java example class names to correct one without breaking the build process?

**Comment by sappo** [comment]
There're should not be any issues regarding the build process. So feel free to send a PR :)

**Comment by esahekmat** [comment]
I saw [[code]] notation with type="example" and name with the name of the file but I can't find out where this notation used with the build system, would you help me to find the location where this [[code]] notation used?

**Comment by sappo** [comment]
Sure, I'll get back to you this evening when I have some free time.

Am 09.03.2018 12:56 nachm. schrieb "Esa Hekmatizadeh" <
notifications@github.com>:

**Comment by esahekmat** [comment]
I create a PR here #725 please take a look at it

**Comment by sappo** [comment]
@esahekmat I just uploaded the updated and new examples. Also there's now a standalone Java zguide version http://zguide.zeromq.org/java:all

**Comment by esahekmat** [comment]
@sappo Thank you a lot.
