### ISSUE TITLE
Paranoid Pirate C++ example

### ISSUE THREAD

**Issue by kreuzerkrieg** [booksbyus/zguide#742]
Hi,
The Paranoid Pirate C++ example doesnt work, the client, for some reason never gets response from queue. When the client initiates the request, it gets to the queue, successfully routed to worker, received and processed by worker, response returned to queue, queue sends it back, however the client does not receives it and dies on timeout.
Looks like [this one](https://stackoverflow.com/questions/24597251/zeromq-issues-with-example-networking-patterns-paranoid-pirate-and-majordomo) is related
Please advise

**Comment by sappo** [comment]
Please send a mail with your issue to the zeromq mailinglist as this issue tracker is rather low latency http://zeromq.org/docs:mailing-lists

**Comment by kreuzerkrieg** [comment]
Done
