### ISSUE TITLE
Java Examples do not compile with latest jeromq (0.4.3)

### ISSUE THREAD

**Issue by amaidment** [booksbyus/zguide#765]
The Java examples (i.e. in ..\zguide-master\examples\Java) do not compile with the latest version of jeromq (0.4.3).

It looks like the main issue are the calls to ZMQ.poll()
For example, in Ppqueue, lines 92/93:
      //  Poll frontend only if we have available workers
      int rc = ZMQ.poll(items, workers.size() > 0 ? 2 : 1, HEARTBEAT_INTERVAL);

However ZMQ.poll() requires a java.nio.channels.Selector
https://static.javadoc.io/org.zeromq/jeromq/0.4.3/zmq/ZMQ.html#poll(java.nio.channels.Selector,%20zmq.poll.PollItem[],%20int,%20long)

**Comment by sappo** [comment]
This issue tracker is not monitored by a lot of people. If you already
solved this problem feel free to send a PR. Otherwise I suggest to write to
the zeromq-dev mailing list.

Am Do., 14. Feb. 2019, 14:47 hat amaidment <notifications@github.com>
geschrieben:

**Comment by amaidment** [comment]
Ok - I'll do that. 

However, I should point out that the very first line of the ZeroMQ guide states: 
"Please use the issue tracker for all comments and errata. "

**Comment by amaidment** [comment]
Having looked at the README for JeroMQ (https://github.com/zeromq/jeromq/blob/master/README.md), there are updated examples for this implementation:

The JeroMQ translations of the zguide examples are a good reference for recommended usage.
(Note that the Java examples in the zguide itself are out of date and do not necessarily reflect current recommended practices with JeroMQ.)

**Comment by sappo** [comment]
@amaidment I just updated the Java examples in the zguide with the examples that are maintained in the JeroMQ repository.
