### ISSUE TITLE
XPUB/XSUB subscription messages direction seems wrong

### ISSUE THREAD

**Issue by shishirpy** [booksbyus/zguide#766]
There is a similar issue: Issue #597 
I think the original text before Issue #597,

> "The proxy has to forward these subscription messages from subscriber side to publisher side, by reading them from the XSUB socket and writing them to the XPUB socket."

was the correct version. Either the current text is incorrect or **Figure 14 - Extended Pub-Sub** is incorrect.

**Comment by guidog** [comment]
Correct me if I'm wrong:
That's the whole point of having XPUB/XSUB. They provide a way to receive/send the subscriptions.
The original reporter confused the data flow of application messages w/ the flow of the subscription control messages.

**Comment by shishirpy** [comment]
@guidog : I think, I am wrong here. I confused the data flow with the subscription control message. Let me know if I am wrong.
