### ISSUE TITLE
[Ask for help] How to understand a REP socket can recv envelope with 3 frames from a DEALER socket ?

### ISSUE THREAD

**Issue by Iflier** [booksbyus/zguide#783]
As mentioned in [this guide](http://zguide.zeromq.org/page:all), "_The ZeroMQ reply envelope formally consists of zero or more reply addresses, followed by an empty frame (the envelope delimiter), followed by the message body (zero or more frames)_",  if we send a multipart message(consists of 3 frames) to a REP socket, and set an addres in the first frame. While I never told which address the REP socket should receive, how can it receive a multipart message with a random address ?

**Comment by sappo** [comment]
Everything you like to know is written in the rfc https://rfc.zeromq.org/spec:28/REQREP/

**Comment by Iflier** [comment]
I got it. @sappo Thanks for your help !
One more question, consider thre following Python code:
`# -*- coding:utf-8 -*-
import time
import json
import platform
import threading

import zmq


address = "inproc://test"
clientNum = 2

print("Python implementation: {0}, python version: {1}".format(platform.python_implementation(), platform.python_version()))
print("Current libzmq version is: {0}".format(zmq.zmq_version()))
print("Current pyzmq version is: {0}".format(zmq.__version__))

def replier(link):
    context = zmq.Context.instance()
    sock = context.socket(zmq.REP)
    sock.connect(link)
    while True:
        content = sock.recv().decode().lower()
        if content in ["exit", "quit"]:
            print("I'm replier, received -> {0}".format(content))
            break
        else:
            print("I'm replier, received -> {0}".format(content))
            sock.send(b"ok")
    sock.close()
    context.term()

def dealer(link):
    context = zmq.Context.instance()
    sock = context.socket(zmq.DEALER)
    sock.bind(link)
    for i in range(5):
        sock.send_multipart([b"happy", b"", ("{0}".format(i)).encode()])
        print("I'm dealer, send -> {0}".format(i))
        print("I'm dealer, received: {0}".format(list(map(lambda x: x.decode(), sock.recv_multipart()))))
    for _ in range(clientNum):
        sock.send_multipart([b"", b"exit"])
    sock.close()
    context.term()

thList = list()
for _ in range(clientNum):
    thList.append(threading.Thread(target=replier, args=(address,)))
thList.append(threading.Thread(target=dealer, args=(address,)))
for th in thList:
    th.start()
for th in thList:
    th.join()

print("Done.")
`
When call `sock.close(); context.term()` at the end of replier func, I got some unexpected message from the terminal:
`Python implementation: CPython, python version: 3.7.2
Current libzmq version is: 4.3.2
Current pyzmq version is: 18.1.0
I'm dealer, send -> 0
I'm replier, received -> 0
I'm dealer, received: ['happy', '', 'ok']
......
I'm dealer, send -> 4
I'm replier, received -> 4
I'm dealer, received: ['happy', '', 'ok']
I'm replier, received -> exit
I'm replier, received -> exit
**Resource temporarily unavailable (bundled\zeromq\src\ctx.cpp:184)**
**Resource temporarily unavailable (bundled\zeromq\src\ctx.cpp:184)**`
While if comment the "sock.close() and context.term()" at the end of replier func, the last two bold lines disappear(**Resource temporarily unavailable (bundled\zeromq\src\ctx.cpp:184)**). May be it is unnecessary to close socket and destroy context in the replier func, am I right ? Thanks in advance !

**Comment by sappo** [comment]
You must use only one context per application.

**Comment by Iflier** [comment]
Ok, I got it. @sappo A good man ! Thanks for your help :-).
