### ISSUE TITLE
Intent of prefix s_ unclear

### ISSUE THREAD

**Issue by franzhollerer** [booksbyus/zguide#800]
The guide gives no indication of what the prefix *s_* used for function and variables is intended for.

Maybe it might be a good idea to state it somewhere.

Looking at zhelpers.h I originally thought *s_* stands for *string* as numerous functions deal with strings. Or it stands for *socket* as most functions deal with sockets likewise.

Then I found that there are other functions like *s_sleep()* and *s_clock()* which don't deal with strings nor sockets.

Furthermore, the C++ example interrupt.cpp defines the gobale variable *s_interrupted* of type *int* and the functions *s_signal_handler()* and *s_catch_signals()*.

I am curious what the prefix stands for. It would be nice if someone could address this topic in the guide.

**Comment by sappo** [comment]
`s_` is an indicator for static method or variables.

**Comment by sappo** [comment]
If you like a hint in regard to those functions, feel welcome to modify the examples with an appropriate comment.
