### ISSUE TITLE
Mistake - should say "Chapter 2" but says "Chapter 3"

### ISSUE THREAD

**Issue by serg06** [booksbyus/zguide#810]
[Chapter 2](http://zguide.zeromq.org/php:chapter2) says "ZeroMQ also supports multipart messages, which let you send or receive a list of frames as a single on-the-wire message. This is widely used in real applications and we'll look at that later in this chapter and in [Chapter 3 - Advanced Request-Reply Patterns](http://zguide.zeromq.org/php:chapter2#advanced-request-reply)."

But as you can see, that link sends you to chapter 2, not chapter 3.

**Comment by shishirpy** [comment]
It is because of the ways the system generates the links. All relative links are of the form `URL#page_link` so instead of using say - `http://zguide.zeromq.org/php:chapter2` if one used 
`http://zguide.zeromq.org/php:all` then the relative links will be correct.

**Comment by serg06** [comment]
Oh it's the link that's broken, my bad.
