### ISSUE TITLE
"Read" link http://zguide.zeromq.org/page:all leads to an empty page

### ISSUE THREAD

**Issue by nikodemuz** [booksbyus/zguide#816]
http://zguide.zeromq.org/page:all

The link leads to an empty page with just the header. This seems to break internal links as well.

Chapter links like http://zguide.zeromq.org/py:chapter1 do work.

**Comment by sappo** [comment]
Thanks for reporting.

It's an wikidot issue where the [[include ..]] tags no have some issues with the chapter1-3 subpages.

**Comment by GabrielDougherty** [comment]
Related discussion at wikidot community [here](http://community.wikidot.com/forum/t-13398270/the-inline-macro-stopped-working)

**Comment by shishirpy** [comment]
Can we use an older wikidot version?

**Comment by sappo** [comment]
The issue seems to be that wikidot restricted the page content size.

So the short term solution will be to print the chapter links onto the all page and the long term goal is to migrate the guide to hugo.

**Comment by sappo** [comment]
page:all now shows the chapter links
