### ISSUE TITLE
SUB or XSUB? 

### ISSUE THREAD

**Issue by timsu92** [booksbyus/zguide#849]
I'm reading zguide, and I can't really understand what I should do [here](../blob/ea1cff3d6308997f5d0a93fa5c5c448ce1abf92f/chapter2.txt#L573-609).

In the diagram, it says I should use XSUB and XPUB, but in the following words, it says I should use SUB and PUB. In the example codes, both are used.
So, what's the one? I guess they all should be XSUB and XPUB right?

**Comment by shishirpy** [comment]
The following section explains why you need the XPUB and XSUB sockets, https://zguide.zeromq.org/docs/chapter2/#The-Dynamic-Discovery-Problem
Look at Figure 14 and the description below it.

**Comment by timsu92** [comment]
Thank you for replying me!

In that section, it tells us that XSUB and XPUB are used as mediators, right?

As [the proxy in figure 18](https://zguide.zeromq.org/docs/chapter2/#ZeroMQ-s-Built-In-Proxy-Function) sits in the between, I guess the figure, which uses "XSUB" and "XPUB", is right, while the text below that says "SUB" and "PUB" is improper.

**Comment by shishirpy** [comment]
Yes, you are right. It should say `XSUB` and `XPUB` in the text.

**Comment by timsu92** [comment]
OK, I'm proposing a PR
