### ISSUE TITLE
zmq guide can not change programming language

### ISSUE THREAD

**Issue by Jzhenli** [booksbyus/zguide#866]
Hi, not sure if it have some issues, I can not change the programming language on the zmq guide web page.

**Comment by sappo** [comment]
Works fine for me. Are you somehow blocking the JavaScript?

**Comment by Jzhenli** [comment]
> Works fine for me. Are you somehow blocking the JavaScript?

have try edge, chrome, firefox and IE, seems all the browser can not works well on the zguide web page.

**Comment by Jzhenli** [comment]
if can export the offline version for the zguide by selected programming language?

**Comment by shishirpy** [comment]
> 
> 
> > Works fine for me. Are you somehow blocking the JavaScript?
> 
> have try edge, chrome, firefox and IE, seems all the browser can not works well on the zguide web page.

I tried all of them and it works fine for me.

**Comment by Jzhenli** [comment]
![img](https://user-images.githubusercontent.com/42105688/132148296-d8d79cc8-9adc-4f4e-af06-3f94b2cf5eef.png)


I clicked the python or some other language, it displayed nothing.

**Comment by sappo** [comment]
You're missing the code blocks all together which are rendered by
JavaScript. See


Jzhenli ***@***.***> schrieb am Mo., 6. Sept. 2021, 03:30:

**Comment by Jzhenli** [comment]
how to fix it? @sappo

**Comment by Jzhenli** [comment]
it still doesn't work,  who can help to fix it?

**Comment by Jzhenli** [comment]
it still doesn't work,  who can help to fix it?

**Comment by Jzhenli** [comment]
have find the root cause, 
replace "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
with“https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js”

it will be ok.
